logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: resttemplate.log
  level:
    org.springframework.web: DEBUG
    org.springframework.web.multipart.support: DEBUG
spring:
  http:
    multipart:
      max-request-size: 200000000
      max-file-size: 200000000

server.port: 18080


